# Pandas

Pandas - это библиотека для работы с табличными данными.

Как всегда, [официальный сайт](https://pandas.pydata.org/) предоставляет самую актуальную и полезную информацию. Доки по функциям и классам [здесь](https://pandas.pydata.org/pandas-docs/stable/reference/index.html).

Установка pandas как обычно не составляет сложностей:

In [ ]:
!pip install pandas==1.0.0

Импорт библиотеки с устоявшимся сокращением:

In [ ]:
import pandas as pd

# Создание объекта таблицы

Начнем с простого создания объекта основного класса в pandas - `DataFrame`. Фреймы в pandas представляют собой двумерные массивы (матрицы) данных. Для применения в машинном обучении визуально можно представить данные следующим образом:

$$
X = 
\begin{bmatrix}
x^{(1)}_1 & \dots & x^{(1)}_{m-1} & x^{(1)}_m \\
x^{(2)}_1 & \dots & x^{(2)}_{m-1} & x^{(2)}_m \\
\vdots & \ddots &  \vdots & \vdots  \\
x^{(n)}_1 & \dots & x^{(n)}_{m-1} & x^{(n)}_m \\
\end{bmatrix}
$$

где $n$ - количество записей (сэмплов/рядов) в данных, $m$ - количество признаков (предикторов/фич) в данных.

> **Признаки** в данных - это те данные, на основе которых производится анализ данных, обучение модели и предсказание. В реальной задаче признаками могут быть "цена", "пол", "группа крови", "текст в заявке" и т.д. [Колонки в таблице]

> **Записи** в данных - сущности, каждая из которых имеет свой набор значений признаков. В базе данных банка это могут быть отдельные транзакции. Все транзакции имеют одинаковые признаки, но значения этих признаков у каждой записи свои. [Строки в таблице]

Создание `DataFrame` возможно разными способами, для начала попробуем создать фрейм из двумерного массива:

In [ ]:
import numpy as np

arr = np.random.randint(0, 10, size=(5, 3))
print(arr)

[[1 6 0]
 [7 5 6]
 [9 9 6]
 [5 8 9]
 [6 6 5]]


In [ ]:
# Создание фрейма - просто вызвать конструктор
df = pd.DataFrame(data=arr)
# Фреймы удобнее отображать с помощью встроенных средств Jupyter
df

0  1  2
0  1  6  0
1  7  5  6
2  9  9  6
3  5  8  9
4  6  6  5

В представленном фрейме важно отметить две особенности:
- Колонки (признаки) имеют имена, но так как мы их (имена) не задали, то они создались автоматически;
- Каждая строка (запись) имеет **уникальный** индекс, тоже создались сами, так как мы не передавали своих индексов.

Для задания имен колонок используется аргумент в конструкторе `columns`, в который передаеся список имен по количеству признаков. Для задания индексов аргумент `index`, в который передается список индексов по количеству записей в массиве.

## Задание

Создайте фрейм с именами колонок `'col_1', 'col_2', 'col_3'` и индексами по алфавиту (`'A', 'B', 'C', ...` или `'A', 'Б', 'В', ...`).

In [ ]:
# TODO
arr = np.random.randint(0, 10, size=(5, 3))
print(arr)

pd.DataFrame(arr,columns=['col_1','col_2','col_3'],index=list('ABCDE'))

[[9 6 7]
 [3 2 8]
 [9 5 5]
 [8 2 6]
 [3 7 9]]


col_1  col_2  col_3
A      9      6      7
B      3      2      8
C      9      5      5
D      8      2      6
E      3      7      9

# Создание фрейма из словарей

Другим способом создания фрейма является конструктор на основе словаря с данными:

In [ ]:
# Создается словарь, в котором ключи будут названиями колонок,
#   а значения - данные по этим колонкам
data = {
    'test_1_mark': [4.6, 3.8, 5.0, 4.5],
    'test_2_mark': [5.0, 3.9, 4.7, 4.5]
}

pd.DataFrame(data)

test_1_mark  test_2_mark
0          4.6          5.0
1          3.8          3.9
2          5.0          4.7
3          4.5          4.5

Альтернативой использования словарей является создание массива словарей:

In [ ]:
# Создается список записей, каждая запись представлена словарем
# В словаре ключи - названия колонок
# При создании фрейма pandas просмотри все возможные ключи словарей в списке
#   и создаст колонок по их названиям
data = [
    {
        'test_1_mark': 4.6,
        'test_2_mark': 5.0
    },
    {
        'test_1_mark': 3.8,
        'test_2_mark': 3.9
    },
    {
        'test_1_mark': 5.0
    },
]

pd.DataFrame(data)

test_1_mark  test_2_mark
0          4.6          5.0
1          3.8          3.9
2          5.0          NaN

Обратите внимание, в одной записи отсутсвовало значение для колонки и во фрейме такое значение обозначено как `NaN`.

> **NaN** (Not a Number) - представление пропусков во фрейме.

Пропуски в данных являение достаточно распространенное. Например, если данные собираются путем анкетирования, то опциональный вопрос может не иметь ответа, поэтому такие записи пропускаются. При разработке моделей машинного обучения с пропусками ведется отдельная работа, но для сырых данных - это нормальное явление.

# Типы данных

Как и в numpy, pandas поддерживает различные типы данных. Для примера создадим фрейм, в котором колонки имеют разные типы данных:

In [ ]:
df = pd.DataFrame({'A': 1.,
                   'B': pd.Timestamp('20130102'),
                   'C': np.array([2.] * 4, dtype='float32'),
                   'D': np.array([3] * 4, dtype='int32'),
                   'E': pd.Categorical(["test", "train", "test", "train"]),
                   'F': 'foo'})
df

A          B    C  D      E    F
0  1.0 2013-01-02  2.0  3   test  foo
1  1.0 2013-01-02  2.0  3  train  foo
2  1.0 2013-01-02  2.0  3   test  foo
3  1.0 2013-01-02  2.0  3  train  foo

Как видите, создается фрейм, в котором каждая колонка имеет свой тип. Из них для нас имеются два новых типа:
- `Timestamp` - конструктор для временного типа в pandas (`datetime64`);
- `Categorical` - категориальный тип, который в большинстве своем является альтернативой численным данным.

> **Категориальные данные** - данные, значения которых ограничены списком категорий (одно из возможных значений);

> **Численные данные** - данные, которые имеют численное значение (вещественное или целочисленное).

Для просмотра информации о фрейме полезно использовать метод `DataFrame.info()`:

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   A       4 non-null      float64       
 1   B       4 non-null      datetime64[ns]
 2   C       4 non-null      float32       
 3   D       4 non-null      int32         
 4   E       4 non-null      category      
 5   F       4 non-null      object        
dtypes: category(1), datetime64[ns](1), float32(1), float64(1), int32(1), object(1)
memory usage: 356.0+ bytes


Если тип данных не задан явно как категориальный, то строки будут иметь тип `object`, как универсальный тип данных.

# Обзор данных

Начало любого анализа данных происходит с того, что мы должны разобраться, с чем имеем дело, поэтому возможности быстрого обзора данных - то, что нужно:

In [ ]:
df = pd.DataFrame(
    data=np.random.randint(-10, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)

# Функция получения первых записей фрейма
# Аргументом задается количество выводимых данных
#   Если не задано - 5 по-умолчанию
df.head(4)

x1  x2  x3
0 -10   9   9
1   2  -1  -2
2  -7   4   8
3  -8  -6   0

In [ ]:
# Функция получения последних записей фрейма
# Аргументом задается количество выводимых данных
#   Если не задано - 5 по-умолчанию
df.tail(4)

x1  x2  x3
11  -3  -6   7
12  -8  -5   6
13   4   8   1
14  -8 -10  -5

In [ ]:
# Функция отображения основной информации о фрейме:
#   Количество записей
#   Типы колонок
#   Количество ненулевых значений
#   Тип индекса
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      15 non-null     int64
 1   x2      15 non-null     int64
 2   x3      15 non-null     int64
dtypes: int64(3)
memory usage: 488.0 bytes


In [ ]:
# Функция отображения статистики по численным колонкам
df.describe()

x1         x2         x3
count  15.000000  15.000000  15.000000
mean   -3.933333  -1.400000   1.066667
std     4.712698   6.333584   6.250333
min   -10.000000 -10.000000  -9.000000
25%    -8.000000  -6.000000  -4.000000
50%    -6.000000  -1.000000   1.000000
75%     0.500000   2.000000   6.500000
max     4.000000   9.000000   9.000000

In [ ]:
# Атрибут получения индексов фрейма
df.index

RangeIndex(start=0, stop=15, step=1)

In [ ]:
# Или чтобы представить в виде списка
list(df.index)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [ ]:
# Атрибут получения имен колонок фрейма
df.columns

Index(['x1', 'x2', 'x3'], dtype='object')

In [ ]:
# Атрибут размерности фрейма
df.shape

(15, 3)

In [ ]:
# Преобразование к двумерному массиву numpy
df.to_numpy()

array([[-10,   9,   9],
       [  2,  -1,  -2],
       [ -7,   4,   8],
       [ -8,  -6,   0],
       [  0,   0,  -9],
       [ -6, -10,  -7],
       [ -8,  -1,  -3],
       [ -2,  -1,   8],
       [  1,   7,   6],
       [ -8,   0,   4],
       [  2,  -9,  -7],
       [ -3,  -6,   7],
       [ -8,  -5,   6],
       [  4,   8,   1],
       [ -8, -10,  -5]])

In [ ]:
# Получение транспонированного представления
# Колонки -> ряды, ряды -> колонки
df.T

# (*) Транспонирование вряд ли часто понадобится при анализе, но учитывать стоит

0  1  2  3  4   5  6  7  8  9  10  11  12  13  14
x1 -10  2 -7 -8  0  -6 -8 -2  1 -8   2  -3  -8   4  -8
x2   9 -1  4 -6  0 -10 -1 -1  7  0  -9  -6  -5   8 -10
x3   9 -2  8  0 -9  -7 -3  8  6  4  -7   7   6   1  -5

# Обращение к данным

Так как данные представлены в виде двумерного массива, то обращение к ним является важным инструментом.

Начнем с того, чтобы обращаться к конкретной колонке:

In [ ]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    columns=['x1', 'x2', 'x3']
)

df

x1  x2  x3
0   4   9   6
1   2   6   4
2   1   4   0
3   2   4   3
4   5   4   9

In [ ]:
print(df['x1'])
print(type(df['x1']))

0    4
1    2
2    1
3    2
4    5
Name: x1, dtype: int64
<class 'pandas.core.series.Series'>


Индексация во фрейме по колонкам производится по имени колонок. В результате создается объект `Series` (ряд), который является одномерным массивом. В случае индексации по колонкам каждая запись в ряду имеет индекс из основного фрейма.

Аналогичный тип данных создается, когда мы обращаемся к конкретной записи в данных. Кстати, просто так не обратиться, поэтому для индексации по записям используются методы `DataFrame.iloc[]` и `DataFrame.loc[]`.

Взгляните на разницу:

In [ ]:
data = {
    'feature1': np.arange(15),
    'feature2': np.linspace(0, 10, 15),
    'feature3': 'string',
}
df = pd.DataFrame(data, index=list('ABCDEFGHIJKLMNO'))
df.head()

feature1  feature2 feature3
A         0  0.000000   string
B         1  0.714286   string
C         2  1.428571   string
D         3  2.142857   string
E         4  2.857143   string

In [ ]:
df.iloc[2]

feature1          2
feature2    1.42857
feature3     string
Name: C, dtype: object

In [ ]:
df.loc['C']

feature1          2
feature2    1.42857
feature3     string
Name: C, dtype: object

In [ ]:
df.iloc[2, 1]

1.4285714285714286

In [ ]:
df.loc['C', 'feature2']

1.4285714285714286

Если разница не явна, то обсудим:
> `.iloc[]` используется для обращения по индексам как рядов, так и колонок;

> `.loc[]` используется для обращения по именованиям как рядов, так и колонок.

В индексации можно применять как слайсы, подобно тем, что научились применять в numpy, так и массивы в качестве индексов.

При индексации по единственной строке создается объект `Series`, но уже с индексами в виде колонок.


## Задание

Выведите часть фрейма со второго ряда по девятый (индексы с 'C' по 'I') и только `feature1` и `feature3`:

In [ ]:
data = {
    'feature1': np.arange(15),
    'feature2': np.linspace(0, 10, 15),
    'feature3': 'string',
}
df = pd.DataFrame(data, index=list('ABCDEFGHIJKLMNO'))
df.head()

feature1  feature2 feature3
A         0  0.000000   string
B         1  0.714286   string
C         2  1.428571   string
D         3  2.142857   string
E         4  2.857143   string

In [ ]:
df.loc[['C','D','E','F','G','H','I'],['feature1','feature3']]
# TODO - выделите часть фрейма с помощью .loc[]

feature1 feature3
C         2   string
D         3   string
E         4   string
F         5   string
G         6   string
H         7   string
I         8   string

In [ ]:
df.iloc[2:9,[0,2]]
# TODO - выделите часть фрейма с помощью .iloc[]

feature1 feature3
C         2   string
D         3   string
E         4   string
F         5   string
G         6   string
H         7   string
I         8   string

# Условная индексация

При работе с данными часто необходимо выбрать часть данных по условному признаку. По аналогии с работой в numpy, применение булевых операторов на ряд данных создает такой же по размеру ряд из булевых элементов, представляющих собой маску:

In [ ]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   6   8   4
1   1   9   9
2   4   2   2

In [ ]:
df['x1'] > 5

0      True
1     False
2     False
3      True
4     False
5      True
6      True
7     False
8      True
9     False
10     True
11    False
12    False
13    False
14     True
Name: x1, dtype: bool

После того, как маска получена, можно применить ее, чтобы выбрать конкретные записи (строки) данных. При этом, индексация маской работает как при использовании `[]`, так и при использовании `.loc[]`.

In [ ]:
mask = df['x1'] > 5
df[mask]

# Или df[df['x1'] > 5]

x1  x2  x3
0    6   8   4
3    8   4   7
5    6   2   0
6    9   4   4
8    7   4   0
10   9   6   3
14   7   4   7

Чтобы получить значения, обратные условию, можно воспользоваться оператором НЕ: `~` - он инвертирует маску условия:

In [ ]:
df[~(df['x1'] > 5)]

x1  x2  x3
1    1   9   9
2    4   2   2
4    2   3   0
7    4   6   9
9    1   2   7
11   1   0   2
12   5   2   2
13   1   3   3

> Как и в numpy, для применения нескольких операций необходимо оборачивать каждую в скобки.

## Задание

Выберите записи во фрейме, которые по признаку `x1` имеют значение больше 3, а по признаку `x3` - меньше 8.

In [ ]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   7   0   8
1   2   1   8
2   1   9   1

In [ ]:
mask = np.logical_and(df['x3'] < 8,df['x1'] > 3)
y = df[mask]
df[mask]
# TODO - отфильтровать фрейм по значениям признаков

x1  x2  x3
4    4   6   0
5    9   6   5
7    8   0   5
8    4   5   6
12   9   9   7

In [ ]:
y.loc[4:12,['x1','x2']]
# TODO - отобразите только колонки x1 и x2 с учетом условий 
#           (используйте .loc[])

x1  x2
4    4   6
5    9   6
7    8   0
8    4   5
12   9   9

## Задание

С помощью метода `DataFrame.query()` получите записи, которые соответсвуют условию сравнения колонок $x1 > x3$:

In [ ]:
df = pd.DataFrame(
    [[1, 2, 6], [5, 1, 1], [8, 4, 6], [4, 1, 1], [9, 9, 0], [-1, 2, 1], [5, 5, 5]],
    columns = ['x1', 'x2', 'x3']
)
df

x1  x2  x3
0   1   2   6
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0
5  -1   2   1
6   5   5   5

In [ ]:
df.query('x1 > x3')
# TODO - Методом DataFrame.query() получить записи, удовлетворяющие условию
#           x1 > x3

x1  x2  x3
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0

In [ ]:
mask = df['x1'] > df['x3']
y = df[mask]
df[mask]
# TODO - Сделать аналогичное действие, но уже с помощью условной индексации

x1  x2  x3
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0

# Операции с рядами / Новые колонки

Работа с фреймами и рядами данных в pandas поддерживает многие операции по аналогии с работой в numpy.

In [ ]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   4   1   0
1   8   7   3
2   0   2   9

In [ ]:
# Создать новую колонку можно по аналогии с новым ключем в словаре
# Сложение нескольких Series и запись в новую колонку
df['x1+x2'] = df['x1'] + df['x2']
df.head(3)

x1  x2  x3  x1+x2
0   4   1   0      5
1   8   7   3     15
2   0   2   9      2

In [ ]:
# Поэлементное умножение
df['x1*x3'] = df['x1'] * df['x3']
df.head(3)

x1  x2  x3  x1+x2  x1*x3
0   4   1   0      5      0
1   8   7   3     15     24
2   0   2   9      2      0

In [ ]:
# Взятие среднего по колонке (метод Series.mean())
df['x1'].mean()

5.133333333333334

In [ ]:
# Использование функций numpy для работы с колонками
df['x2_exp'] = np.exp(df['x2'])
df.head(3)

x1  x2  x3  x1+x2  x1*x3       x2_exp
0   4   1   0      5      0     2.718282
1   8   7   3     15     24  1096.633158
2   0   2   9      2      0     7.389056

Как вы заметили, ряды (это же одномерные массивы) можно обрабатывать:
- операциями Python;
- методами класса Series;
- функциями numpy.

> Для создания новой колонки достаточно просто задать имя новой колонки и записать ряд данных (может быть даже одномерным массивом numpy), который имеет такой же размер, куда пишется.

Для случая, если нужной функции нет, то можно создать свою с помощью метода `Series.apply()`, которой передается название функции для применения над всем рядом.

In [ ]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(3, 3)), 
    columns=['x1', 'x2', 'x3']
)
df

x1  x2  x3
0   4   3   5
1   1   3   2
2   9   3   3

In [ ]:
# Обязательно требование к функции - один аргумент
# Эта функция будет передана в apply() и pandas
#   будет вызывать ее и передавать в нее 
#   по одному элементу из ряда
# Возвращать функция должна результат операции над элементом
def my_func(x):
    print(type(x))
    print(x)
    return x*2

df['result'] = df['x1'].apply(my_func)
df

<class 'int'>
4
<class 'int'>
1
<class 'int'>
9


x1  x2  x3  result
0   4   3   5       8
1   1   3   2       2
2   9   3   3      18

Как видно, в функцию передается каждый элемент в ряду, тип элемента соответсвует типу колонки. Результат метода `.apply()` - новый ряд с примененной функцией.

# Операции с фреймами

## Переименование колонок / индексов

Одной из полезных функций является возможность переименования имен колонок. Для этого имеется метод `DataFrame.rename()`:

In [ ]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   4   8   5
1   6   8   3
2   1   5   5

In [ ]:
# Методу передается в аргумент columns словарь, 
#   в котором ключи - имена колонок,
#   значения - новые имена для переименования
df.rename(
    columns={
        'x1': 'new_name_for_x1',
        'x3': 'that_not_x3' 
    },
    inplace=True
)
df.head(3)

new_name_for_x1  x2  that_not_x3
0                4   8            5
1                6   8            3
2                1   5            5

> Аргумент `inplace` является достаточно распространенным в методах фреймов. Этот аргумент управляет тем, как произвести операцию: прямо в этом классе (при установленном True) или вернуть результатом новый фрейм с произведенной операцией (при установленном False).

Для сравнения аналогичный код без `inplace` выглядел бы так:
```python
df_renamed = df.rename(columns={
    'x1': 'new_name_for_x1',
    'x3': 'that_not_x3'
})
df_renamed
```

Для переименования индексов (названий записей) используется тот же принцип, но словарь передается в аргумент `index` с ключами - исходными названиями индексов, значениями - новыми значениями.

### Задание

Переименуйте индексы и колонки во фрейме

In [ ]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    index=['A', 'B', 'C', 'D', 'E'], 
    columns=['x1', 'x2', 'x3']
)
df

x1  x2  x3
A   9   0   2
B   3   6   8
C   1   4   9
D   3   2   3
E   7   6   9

In [ ]:
df_renamed = df.rename(columns={
    'x1': 'new1',
    'x3': 'new3'
},index={
    'A': 'indA',
    'C': 'indC'
})
df_renamed
# TODO - переименуйте индексы [A, C] -> [indA, indC] 
#           и колонки [x1, x3] -> [new1, new3]

new1  x2  new3
indA     9   0     2
B        3   6     8
indC     1   4     9
D        3   2     3
E        7   6     9

## Удаление колонок / строк

Данную операцию можно произвести двумя способами:
1. Выбрать колонки, которые необходимо оставить, простой индексацией;
2. Метод `DataFrame.drop()`.

In [ ]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   8   9   4
1   9   0   8
2   6   6   5

In [ ]:
df.drop(columns=['x2'], inplace=True)
df.head(3)

x1  x3
0   8   4
1   9   8
2   6   5

## Определение количества NaN

В данных часто бывают пропуски (NaN), при этом на первых этапах анализа важно понять их количество по каждому признаку. Для этого можно воспользоваться методом `DataFrame.isna()`, который создаст двумерный булевый фрейм, отвечающий на вопрос "является ли значение NaN?". После этого над всем фреймом можно применить метод `DataFrame.sum()`, который вернет ряд (Series) с количеством элементов True в булевом фрейме (элементов NaN в основном фрейме).

In [ ]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.iloc[0, :2] = np.nan
df.iloc[2, 1:] = np.nan

df

x1   x2   x3
0  NaN  NaN  0.0
1  6.0  7.0  1.0
2  0.0  NaN  NaN
3  9.0  1.0  0.0
4  5.0  6.0  7.0

In [ ]:
df.isna()

x1     x2     x3
0   True   True  False
1  False  False  False
2  False   True   True
3  False  False  False
4  False  False  False

In [ ]:
df.isna().sum()

x1    1
x2    2
x3    1
dtype: int64

## Заполнение пустых значений

Техники заполнения пустых значений имеют разнообразное представление, но одним из простых методов является заполнение константой. Для этого ряд данных имеет метод `Series.fillna()`, в который можно передать значение и вместо NaN элементов будет поставлена константа, указанная в аргументах.

In [ ]:
df

x1   x2   x3
0  NaN  NaN  0.0
1  6.0  7.0  1.0
2  0.0  NaN  NaN
3  9.0  1.0  0.0
4  5.0  6.0  7.0

In [ ]:
df['x2'].fillna(3, inplace=True)
df

x1   x2   x3
0  NaN  3.0  0.0
1  6.0  7.0  1.0
2  0.0  3.0  NaN
3  9.0  1.0  0.0
4  5.0  6.0  7.0

## Информация об уникальных значениях



При работе с категориальными данными полезна информация об уникальных значения признака, поэтому важно понимать, как проверить их количество:

In [ ]:
df = pd.DataFrame({
    'col1': ['high', 'high', 'low', 'med', 'low', 'low', 'med', 'low', 'low', 'high'],
    'col2': [0, 1, 1, 2, 3, 1, 1, 2, 2, 2]
})
df

col1  col2
0  high     0
1  high     1
2   low     1
3   med     2
4   low     3
5   low     1
6   med     1
7   low     2
8   low     2
9  high     2

In [ ]:
# Метод DataFrame.nunique() позволяет вывести 
#   количество уникальных значений в каждой колонке
# Результат - Series с индексами - названиями колонок
df.nunique()

col1    3
col2    4
dtype: int64

In [ ]:
# Метод Series.value_counts() показывает уникальные значения в ряду
#   и указывает их количество
df['col1'].value_counts()

low     5
high    3
med     2
Name: col1, dtype: int64

In [ ]:
# Результат - Series с индексами - уникальными значениями
df['col2'].value_counts()

2    4
1    4
3    1
0    1
Name: col2, dtype: int64

## Фильтрация

Метод `DataFrame.filter()` позволяет отфильтровать и выбрать только те колонки/записи, котрые соответсвуют условию, заданному в аргументах:

In [ ]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6])),
                  index=['mouse', 'rabbit'],
                  columns=['col_one', 'col_two', 'col_three'])
df

col_one  col_two  col_three
mouse         1        2          3
rabbit        4        5          6

In [ ]:
# Отфильтровать по именам колонок
# Аналогично df[['col_one', 'col_three']]
df.filter(items=['col_one', 'col_three'], axis='columns')

col_one  col_three
mouse         1          3
rabbit        4          6

In [ ]:
# Отфильтровать по регулярному выражению
# Оставить только те колонки, которые оканчиваются на букву "o"
df.filter(regex='o$', axis='columns')

col_two
mouse         2
rabbit        5

### Задание

Отфильруйте записи по строке, содержащейся в имени индекса (аргумент `like`):

In [ ]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9])),
                  index=['dog in house', 'cat in house', 'pig in farm'],
                  columns=['x1', 'x2', 'x3'])
df

x1  x2  x3
dog in house   1   2   3
cat in house   4   5   6
pig in farm    7   8   9

In [ ]:
df.filter(like='house', axis=0)
# TODO - отфильтруйте по записям, должны остаться записи, 
#           индекс которых содержит слово "house"

x1  x2  x3
dog in house   1   2   3
cat in house   4   5   6

## Сортировка

Всегда полезно знать, как отсортировать данные, для этого мы воспользуемся методом `DataFrame.sort_values()`:

In [ ]:
df = pd.DataFrame({
    'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col2': [2, 1, 9, 8, 7, 4],
    'col3': [0, 1, 9, 4, 2, 3],
    'col4': ['a', 'B', 'c', 'D', 'e', 'F']
}, index=['A', 'B', 'C', 'D', 'E', 'F'])
df

col1  col2  col3 col4
A    A     2     0    a
B    A     1     1    B
C    B     9     9    c
D  NaN     8     4    D
E    D     7     2    e
F    C     4     3    F

In [ ]:
# Отсортируем записи колонки col2
# Именно поэтому в axis ставится rows, так как
#   операция производится в колонке по каждому ряду
df.sort_values(by='col2', axis='rows')

col1  col2  col3 col4
B    A     1     1    B
A    A     2     0    a
F    C     4     3    F
E    D     7     2    e
D  NaN     8     4    D
C    B     9     9    c

### Задание

Отсортируйте данные:

In [ ]:
df = pd.DataFrame(
    np.random.randint(0, 20, size=(5, 5)), 
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)
df

col1  col2  col3  col4  col5
0     7     5     1     6     5
1    14    10    16     3    19
2    15    17     3     5    16
3    11    13    13     0    10
4     3     6     1     6    19

In [ ]:
df.sort_values(by=3,axis=1,ascending=False)
# TODO - отсортируйте данные индекса 3 по убыванию

col2  col3  col1  col5  col4
0     5     1     7     5     6
1    10    16    14    19     3
2    17     3    15    16     5
3    13    13    11    10     0
4     6     1     3    19     6

## Разделение данных на категории

В ходе работы с данными часто бывает необходимо диапазон числовой переменной разбить на несколько групп (категорий). Например, заменить числовой диапазон температур воды $[-10; 60]$ на три категории $[низкая, средняя, высокая]$. Для таких целей используется функция `pd.cut()`:

In [ ]:
df = pd.DataFrame({
    'temp': [59, 22, -10, 38, 20, 40, 38, 47, 20, 15, 13, 44, 57, 32, 38]
})
df.head()

temp
0    59
1    22
2   -10
3    38
4    20

In [ ]:
# Можно задать свои границы диапазона и названия категорий
# Если планируется три категории, то границ должно быть на одну больше - 
#   так задаются диапазоны для категорий
df['temp_cat'] = pd.cut(
    x=df['temp'],
    bins=[-10, 10, 25, 60],
    labels=['low', 'medium', 'high'],
    # Флаг, чтобы самое левое значение границы входило в первый диапазон
    include_lowest=True
)
df.head()

temp temp_cat
0    59     high
1    22   medium
2   -10      low
3    38     high
4    20   medium

In [ ]:
# Результат разделения имеет категориальный тип
df['temp_cat'].dtype

CategoricalDtype(categories=['low', 'medium', 'high'], ordered=True)

In [ ]:
# Можно не задавать имена категориям, тогда он сам их назовет
result_after_cut = pd.cut(
    x=df['temp'],
    bins=[-10, 10, 25, 60],
    include_lowest=True
)
# Взглянем на имена
result_after_cut.unique()

[(25.0, 60.0], (10.0, 25.0], (-10.001, 10.0]]
Categories (3, interval[float64]): [(-10.001, 10.0] < (10.0, 25.0] < (25.0, 60.0]]

In [ ]:
# Можно не задавать границы, лишь количество категорий - 
#   разделение будет на категории с одинаковой шириной диапазонов
result_after_cut = pd.cut(
    x=df['temp'],
    bins=3
)
result_after_cut.unique()

[(36.0, 59.0], (13.0, 36.0], (-10.069, 13.0]]
Categories (3, interval[float64]): [(-10.069, 13.0] < (13.0, 36.0] < (36.0, 59.0]]

### Задание

Разделите показатель качества в диапазоне $[0, 100]$ на три группы: плохое $[0-20]$, среднее $(20-45]$, хорошее $(45-85]$, отличное $(85-100]$. Выясните, что происходит со значениями, которые не попадают в диапазоны категорий:

In [ ]:
df = pd.DataFrame({
    'quality': [ 7, 67, 21, 38,  2, -2, 79, 22,  5, 31, 77, 72, 23, 64, 99]
})
df.head()

quality
0        7
1       67
2       21
3       38
4        2

In [ ]:
df['temp_cat'] = pd.cut(
    x=df['quality'],
    bins=[0, 20, 45, 85, 100],
    labels=['bad', 'medium', 'good', 'excellent'],
    # Флаг, чтобы самое левое значение границы входило в первый диапазон
    include_lowest=True
)
df
#не имеют категорий те, которые не входят в диапазон
# TODO - разделите данные на категории
# TODO - определите, какие записи не имеют категорий и почему

quality   temp_cat
0         7        bad
1        67       good
2        21     medium
3        38     medium
4         2        bad
5        -2        NaN
6        79       good
7        22     medium
8         5        bad
9        31     medium
10       77       good
11       72       good
12       23     medium
13       64       good
14       99  excellent

## Агрегация данных

Агрегация данных - объединение группы данных для получения информации. Примерами операций аргегации являются: сумма, среднее, максимум, минимум.

В pandas агрегация может быть выполнена путем метода `DataFrame.aggregate()`:

In [ ]:
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [np.nan, np.nan, np.nan]],
                  columns=['A', 'B', 'C'])
df

A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [ ]:
# Получим значения минимумов и средних по всем колонкам
# Принцип аналогичен операциям в numpy - 
#   для агрегации по колонка операция должна пройти по рядам,
#   соответсвенно, axis='rows'
df.aggregate(['min', 'mean'], axis='rows')

A    B    C
min   1.0  2.0  3.0
mean  4.0  5.0  6.0

In [ ]:
# Зададим правила агрегации для каждой колонки
# Операции можно задавать строками или функциями numpy
df.aggregate({
    'A': ['sum', 'min'],
    'B': ['max', 'min'],
    'C': [np.sum, np.mean],
})

A    B     C
max    NaN  8.0   NaN
mean   NaN  NaN   6.0
min    1.0  2.0   NaN
sum   12.0  NaN  18.0

### Задание

Произведите агрегацию средним по рядам

In [ ]:
df = pd.DataFrame(
    ([1, 2, 3], [4, 5, 6], [7, 8, 9]), 
    columns=['x1', 'x2', 'x3'])
df

x1  x2  x3
0   1   2   3
1   4   5   6
2   7   8   9

In [ ]:
df.aggregate('mean', axis='columns')
# TODO - произведите агрегацию по рядам (найти среднее)

0    2.0
1    5.0
2    8.0
dtype: float64

## Группировки

Игры закончились - начались серьезные вещи. Группировки это один из сильнейших инструментов, которые позволяют вытаскивать из данных полезную информацию!

Для понимания разберем пример: допустим, у нас есть база данных студентов с 1 по 4 курсы. Одна из колонок будет иметь в качестве значения номер курса и так как количество допустимых значений ограничено - то правильно считать эту колонку категориальной. Другая колонка - оценка за общий университетский тест (все курсы его проходили). Третьей колонкой будет время выполнения:

In [ ]:
data = [
    [1, 4.7, 60],
    [3, 4.5, 45],
    [4, 4.8, 40],
    [1, 4.9, 58],
    [2, 4.1, 50],
    [2, 4.2, 49],
    [2, 4.4, 49],
    [3, 4.9, 46],
    [4, 4.3, 33],
]

stud_df = pd.DataFrame(data, columns=['Grade', 'Test_Mark', 'Time'])
stud_df

Grade  Test_Mark  Time
0      1        4.7    60
1      3        4.5    45
2      4        4.8    40
3      1        4.9    58
4      2        4.1    50
5      2        4.2    49
6      2        4.4    49
7      3        4.9    46
8      4        4.3    33

Теперь представим, что мы сложим каждый курс в свою корзинку путем группировки:


In [ ]:
gr_stud_df = stud_df.groupby(by='Grade')

# Тип результата - pd.DataFrameGroupBy
print(type(gr_stud_df))

# Таким образом увидим словарь:
#   Ключи - названия групп
#   Значения - индексы из данных для группы
gr_stud_df.groups

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


{1: Int64Index([0, 3], dtype='int64'),
 2: Int64Index([4, 5, 6], dtype='int64'),
 3: Int64Index([1, 7], dtype='int64'),
 4: Int64Index([2, 8], dtype='int64')}

После того, как мы сложили записи по группам, мы можем вычислить, например, среднее значение в каждой группе:

In [ ]:
gr_stud_df.agg('mean')

Test_Mark       Time
Grade                      
1       4.800000  59.000000
2       4.233333  49.333333
3       4.700000  45.500000
4       4.550000  36.500000

В результате, мы смогли вычислить среднюю оценку за тест по каждому курсу! И для этого нам потребовалось всего два метода! Ручным вариантом нам бы пришлось создавать контейнеры, складывать в них значения и потом вычислять средние значения...

Резюмируя, группировка - это размещение данных по группам уникальных значений признака, по которому группируется. После группировки можно произвести агрегацию данных в каждой группе.

In [ ]:
# Более сложный вариант - найдем средние и минимальные время и оценку 

gr_stud_df.agg(['mean', 'min'])

Test_Mark            Time    
           mean  min       mean min
Grade                              
1      4.800000  4.7  59.000000  58
2      4.233333  4.1  49.333333  49
3      4.700000  4.5  45.500000  45
4      4.550000  4.3  36.500000  33

In [ ]:
# Или зададим правила для каждого признака по отдельности

res = gr_stud_df.agg({
    'Test_Mark': ['mean', 'min'],
    'Time': ['min']
})

print(type(res))
res

<class 'pandas.core.frame.DataFrame'>


Test_Mark      Time
           mean  min  min
Grade                    
1      4.800000  4.7   58
2      4.233333  4.1   49
3      4.700000  4.5   45
4      4.550000  4.3   33

In [ ]:
# Для обращения к данным просто используем несколько индексов, 
#   так как это DataFrame
res['Test_Mark']['mean']

Grade
1    4.800000
2    4.233333
3    4.700000
4    4.550000
Name: mean, dtype: float64

### Задание

Сгруппируйте данные по признаку x2 и найдите медиану и максимальное значения по признакам x1, x3:

In [ ]:
df = pd.DataFrame({
    'x1': np.random.randint(10, 100, size=(200, )),
    'x2': np.random.choice(['low', 'high', 'medium'], size=(200, )),
    'x3': np.random.randint(-20, 30, size=(200, )),
})
df.head()

x1      x2  x3
0  49    high  16
1  49  medium -11
2  20    high -13
3  21    high  12
4  32     low  20

In [ ]:
print(df.groupby(['x2']).mean())
print(df.groupby(['x2']).max())
# TODO - произведите групировку данных
#           и получите средние и максимальные значения по каждой группе

               x1        x3
x2                         
high    52.517241  4.137931
low     52.632353  5.220588
medium  55.216216  8.202703
        x1  x3
x2            
high    97  29
low     99  29
medium  99  29


# Сохранение / загрузка данных (работа с CSV)

Одним из важных инструментов в работе с таблицами является возможность сохранить результаты работы в файл или загрузить данные из файла. Пользоваться мы будем форматом CSV, который является текстовым форматом для хранения таблицы. Формат представляет собой текстовые строки, каждая колонка разделяется разделителем (запятая, точка запятой и др.), поэтому его просто понять и обрабатывать, так как не требуется никакого специального протокола для понимания.

Для сохранения данных имеется метод `DataFrame.to_csv()`:

In [ ]:
import string

df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df.head(3)

x1  x2  x3
A   4   3   0
B   6   7   2
C   2   6   7

In [ ]:
# Для сохранения задается путь до файла
df.to_csv('my_first_file.csv')

Чтобы убедиться в работе метода найдите файл рядом с ноутбуком и откройте его через редактор.

> При работе в Google Colab слева есть вкладка, которая показывает файлы на сервере.

При открытии можно увидеть четыре колонки:
- Колонка индекса;
- Три колонки из наших данных.

Теперь, когда мы имеем файл CSV в системе - можем испытать функцию загрузки `pd.read_csv()`:

In [ ]:
df = pd.read_csv('my_first_file.csv')
df.head(3)

Unnamed: 0  x1  x2  x3
0          A   4   3   0
1          B   6   7   2
2          C   2   6   7

Видна одна явная проблема - у нас появилась колонка, которая должна быть индексом, но она стала новой колонкой, а индексы создались новые. Для решения проблемы при загрузке необходимо явно задать, какая колонка считается индексом:

In [ ]:
df = pd.read_csv('my_first_file.csv', index_col=0)
df.head(3)

x1  x2  x3
A   4   3   0
B   6   7   2
C   2   6   7

Теперь все отлично и данные загрузились так, как они должны быть.

## Задание

Разберитесь в аргументах `DataFrame.to_csv()` и сохраните данные в файл так, чтобы в файл индекс не сохранялся.

In [ ]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df.head(3)

df.to_csv('no_index.csv',index=False)

# TODO - сохранить в файл no_index.csv без индексов

# Задачки


Создайте фрейм с тремя колонками:
- Колонка с именами (тип - объекты);
- Колонка с стажем работы (тип - вещественный);
- Колонка с возрастом (тип - целочисленный);
- Колонка с названием любимого цвета (тип - категориальный);

Имена колонок и значения любые, не менее трех записей (строк) в фрейме.

In [ ]:
x1 = np.array(['Александр', 'Евгения', 'Анна'], dtype="object")
x2 = np.array([2.1, 3.2, 4.1], dtype=np.float64)
x3 = np.array([19, 20, 21], dtype=np.int64)
df = pd.DataFrame({
    'Name': x1,
    'Work Experience': x2,
    'Age': x3,
    'Favourite Color': pd.Categorical(["Blue", "Green", "Black"])
}, index=[1, 2, 3])
df.dtypes
#df
# TODO - создайте фрейм и настройте правильные типы колонок
#           DataFrame.info() дожен отображать указанные типы

Name                 object
Work Experience     float64
Age                   int64
Favourite Color    category
dtype: object

Выберите числа в ряду `ds1`, которых нет в ряду `ds2`:

> Почитайте и примение метод `Series.isin()`

In [ ]:
ds1 = pd.Series([1, 2, 3, 4, 5])
ds2 = pd.Series([4, 5, 6, 7, 8, 1, 9])

y = [1, 2, 3, 4, 5]
c = []
for i in y:
  z = ds2.isin([i])
  if not np.any(z):
    c = np.append(c,i)
    c = np.int64(c)
print(list(c))
# TODO - выберите значения в ds1, которых нет в ds2: 
# [2, 3]

[2, 3]


Оставьте в ряду два наиболее частых значения, остальные замените значением 'Другое':

<details>
<summary>Подсказка 1</summary>

Для определения наиболее частых значений воспользуйтесь методом `Series.value_counts()`
</details>

<details>
<summary>Подсказка 2</summary>

Чтобы получить наиболее частые значения можно воспользоваться результатом `Series.value_counts()` - атрибутом `Series.index`
</details>

<details>
<summary>Подсказка 3</summary>

Получив наиболее частые значения, можно индексировать другие через маску метода `Series.isin()`
</details>


In [ ]:
ds = pd.Series([2, 2, 2, 4, 4, 4, 3, 1, 1, 1, 1, 4])

counts = ds.value_counts()
mf = counts.index[0]
smf = counts.index[1]

j = 0
for i in ds:
  if i != mf:
    if i != smf:
      ds[j] = "Другое"
  j=j+1
ds
# TODO - определите два наиболее частых значения в ряду (1, 4),
#           остальные замените значением 'Другое'
# ['Другое', 'Другое', 'Другое', 4, 4, 4, 'Другое', 1, 1, 1, 1, 4]

0     Другое
1     Другое
2     Другое
3          4
4          4
5          4
6     Другое
7          1
8          1
9          1
10         1
11         4
dtype: object

Сделайте каждую первую букву в словах ряда заглавной:

In [ ]:
ds = pd.Series(['how', 'to', 'use', 'pandas?'])

ds = ds.str.capitalize()
print(ds)
# TODO - сделайте каждую первую букву заглавной с помощью Series.apply()

0        How
1         To
2        Use
3    Pandas?
dtype: object


Выберите записи с максимальным значением по колонке `x1`:

In [ ]:
df = pd.DataFrame(
    np.random.randint(0, 4, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
print(df)
for i in range(15):
  if df.values[i][0] == df.max()[0]:
    print(df.values[i])
# TODO - выберите те записи, которые имеют x1 равный 
#           максимальному значению в колонке x1

    x1  x2  x3
0    1   3   0
1    0   2   3
2    1   2   3
3    3   2   0
4    1   2   1
5    3   3   0
6    0   0   0
7    2   0   2
8    2   1   3
9    2   0   0
10   2   3   3
11   3   1   2
12   2   2   2
13   2   0   1
14   1   3   0
[3 2 0]
[3 3 0]
[3 1 2]


Выведите количество пропусков в каждой колонке данных:

In [ ]:
import math
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')
k  = pd.value_counts(df.values.flatten())

print(df.isna().sum().sum())
# TODO - отобразите количество пропусков в данных по каждой колонке

138


Замените пропущенные значения в колонке `Min.Price` средним значениям по этой колонке:

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')

min_price_nan = 7
min_price_non_nan = 93-7
count = 0
for i in range(93):
  res = df.values[:,3][i]
  if (res!=res) is False:
    count = count + res
mn = count/min_price_non_nan
df.replace("nan",mn)
df['Min.Price'] = df['Min.Price'].fillna(mn)
print(df.values[:,3])
# TODO - заполните NaN в колонке Min.Price средним значением по этой колонке
# NOTE - после заполнения убедитесь, что в этой колонке нет пропущенных

[12.9 29.2 25.9 17.11860465116279 17.11860465116279 14.2 19.9 22.6 26.3
 33.0 37.5 8.5 11.4 13.4 13.4 14.7 14.7 18.0 34.6 18.4 14.5 29.5 7.9 8.4
 11.9 17.11860465116279 14.8 18.5 7.9 17.11860465116279 6.9 8.4 10.4 10.8
 12.8 14.5 15.6 20.1 6.7 11.5 17.0 8.4 13.8 6.8 9.0 9.1 12.4 45.4 27.5
 34.7 33.3 34.4 7.4 10.9 14.3 16.6 32.5 29.0 43.8 13.3 14.9 7.7 22.4 8.7
 13.0 16.7 21.0 13.0 14.2 19.5 19.5 11.4 17.11860465116279 9.4 14.0 15.4
 19.4 20.3 9.2 7.3 10.5 16.3 7.3 17.11860465116279 14.2 15.2
 17.11860465116279 8.7 16.6 17.6 22.9 21.8 24.8]


Отсортируйте и выведите фрейм с колонками в алфавитном порядке:

In [ ]:
df = pd.DataFrame(np.random.randint(0, 10, size=(5, 6)), columns=list('fbecda'))

print(df.sort_index(axis=1,ascending=False))
# TODO - получите фрейм с отсортированными по именам колонкам (f e d c b a)
# NOTE - сортировка должна быть автоматической

   f  e  d  c  b  a
0  1  3  8  4  3  7
1  1  5  3  6  2  1
2  9  9  1  2  0  7
3  6  2  8  9  3  0
4  0  9  5  8  2  6


Отобразите каждую 20ю запись во фрейме и только колонки `Manufacturer`, `Model`, `Type`:

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')

print(df.values[20,0:2])
print(df.values[40,0:2])
print(df.values[60,0:2])
print(df.values[80,0:2])
# TODO - отобразите запись с периодичностью во фрейме и определенные колонки

['Chrysler' 'LeBaron']
['Honda' 'Prelude']
['Mercury' 'Cougar']
['Subaru' 'Loyale']


Получите ряд, который содержит длины строк:

In [ ]:
ds = pd.Series(['how', 'to', 'use', 'pandas?'])

pr = pd.Series([len(ds.values[0]),len(ds.values[1]),len(ds.values[2]),len(ds.values[3])])
pr
# TODO - создайте ряд, содержащий длины строк:
# 0    3
# 1    2
# 2    3
# 3    7
# dtype: int64

0    3
1    2
2    3
3    7
dtype: int64